3NF
CREATE TABLE PRODUCT_CUSTOMER TABLE(
    CustomerID INT PRIMARY KEY,
    CustomerName VARCHAR(45),
    Email VARCHAR(45),
);
CREATE TABLE TRAVEL_CUSTOMER TABLE(
    CustomerID INT PRIMARY KEY,
    CustomerName VARCHAR(45),
    Email VARCHAR(45)
);
CREATE TABLE FARM INPUT_CUSTOMER TABLE(
    CustomerID INT PRIMARY KEY,
    CustomerName VARCHAR(45),
    Email VARCHAR(45),
);